### ISSUE TITLE
Help with testing / development

### ISSUE THREAD

**Issue by Astrographltd** [photon1503/NINA.Photon.Plugin.ASA#1]
Hi, I am ASA's partner in the UK. We have just started to explore NINA as an option for use with ASA client systems, based on your plugin.

We have just setup a trial system but note that with Autoslew 5.3.0.2 at least, it does not seem possible to use an ASA mount with NINA.

There seem to be many problems;

Use of the Ascom driver results in an error, 1 sec after it says connected.
Use via Ascom Device Hub issues a time error
There is no tracking state info. Infact the mount page layout in NINA seems like it was original intended for a 10M mount (i.e. 'Unpark')
Movement typically causes an error

I am wondering therefore which version of Autoslew you tested this under? 5.3.0.2 is the last version of Autoslew that supports the original licence key and therefore the mounts made before the DDM100,200 and 500.

Versions after this require a new licence FILE. These versions (and the new versions of Sequence) will not be available for legacy mounts.

ASA plan to release a new version of Sequence for the legacy mounts but the timeline is unknown and it will not contain all the features of the latest version.

As such, we want to offer our clients (and the legacy ASA community generally) and alternative. New DDM users also may benefit. Therefore it would be good to know how you got this plug in working as we cannot!

For the future, we would also like to explore the possibility of creating an MLPT type function if you think this might be possible? We are in the fortunate position of having access to a wide range of mounts and software versions for testing.

Best Regards

Rupert Smith
Astrograph Ltd
rupert@astrograph.net

**Comment by photon1503** [comment]
Dear Rupert,

thank you for your message. Unfortuantely this driver is only for legacy ASA DDM mounts (DDM 60, 85) where the users are locked to Autoslew 5.2.4.8

Users with newer mounts like DDM 100 have a completely different Autoslew version which is not compatible with this driver.

But you can use ASCOM Alpace to connect from NINA to DDM 100, this is working an does not need any additional driver.

Gerald

**Comment by photon1503** [comment]
closed as it not a technical issue related to this project

**Comment by photon1503** [comment]
closed
